<?php

/**
 * @file
 * Bootstrap styles module.
 */

/**
 * Implements hook_theme().
 */
function bootstrap_styles_theme() {
  return [
    'bs_video_background' => [
      'variables' => [
        'video_background_url' => '',
        'attributes' => [],
        'children' => [],
      ],
    ],
  ];
}

/**
 *
 */
function bootstrap_styles_page_attachments_alter(array &$page) {
  // Attach the asset on every page.
  $page['#attached']['library'][] = 'bootstrap_styles/offcanvas-font';
  $page['#attached']['library'][] = 'bootstrap_styles/theme.dark';
  // $page['#attached']['library'][] = 'bootstrap_styles/theme.light';
}
